     
server:
  port: 8082

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "user"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8081/login/oauth2/code/client-1"
                - "http://localhost:8081/authorized"
              scopes:
                - "user.read"
                - "user.write"
              token:
              access-token-time-to-live: 3000s  
#            require-authorization-consent: true
          client-2:
            registration:
              client-id: "admin"
              client-secret: "{bcrypt}$2a$10$CFfGAlt3jvHuUOYGtz8/auZ2.54xWglgAvrZNVMct.rcl.AF/muNi"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8081/login/oauth2/code/client-1"
                - "http://localhost:8081/authorized"
              scopes:
                - "admin.audit"
              token:
              access-token-time-to-live: 300000s